#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xsetroot -cursor_name left_ptr
pulseaudio --start 
input-remapper-control --command autoload

if [ $(xrandr -q | grep " connected" | grep -v eDP | cut -d" " -f1) = "HDMI-A-0" ]; then
	xrandr --output eDP --primary --mode 1920x1080 --rotate normal --output HDMI-A-0 --mode 1920x1080 --rotate normal --above eDP;

    bspc monitor eDP -d II III IV V VI VII VIII IX X
    bspc monitor HDMI-A-0 -d I
else
    bspc monitor eDP -d I II III IV V VI VII VIII IX X
fi

bspc config border_width         2
bspc config window_gap           9

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=of

# Feh background
feh --bg-fill ~/Desktop/v4sr/Images/wallpaper.png

# Polybar
~/.config/polybar/./launch.sh

# Picom
picom --experimental-backends &

# bspwm
bspc config focus_follows_pointer false
bspc config border_width 0
